# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
name: "build"

on:
  push:
    branches:
    - release-1.7*
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:

  config:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.config.outputs.image }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - id: config
      run: |
        IMG=$( make default RUN='printenv IMG #' )
        echo "::set-output name=image::${IMG}" # ISTIO_BUILD_TOOLS

  build:
    needs: config
    runs-on: ubuntu-latest

    container:
      image: ${{ needs.config.outputs.image }} # ISTIO_BUILD_TOOLS
      env:
        BUILD_WITH_CONTAINER: "0"

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - run: make presubmit

  gencheck:
    needs: config
    runs-on: ubuntu-latest

    container:
      image: ${{ needs.config.outputs.image }} # ISTIO_BUILD_TOOLS
      env:
        BUILD_WITH_CONTAINER: "0"

    steps:
    - name: "Install latest `git`"
      run: |
        apt-get purge git -y
        add-apt-repository ppa:git-core/ppa -y
        apt-get update && apt-get install -y --no-install-recommends \
            git \
         && apt-get clean \
         && rm -rf /var/lib/apt/lists/*

    - name: "Checkout"
      uses: actions/checkout@v2

    - run: make gen-check
